docs(translate): TSPL
SwiftGGTeam/swift-org-website pull request #70
Opened 2024-12-28 04:02 UTC by szupzj18

翻译内容

文件路径：documentation/api-design-guidelines
closed https://github.com/SwiftGGTeam/swift-org-website/issues/9

翻译检查清单

 - [x] 已检查专业术语一致性
 - [x] 已进行本地预览测试
 - [x] 保持了原文格式
 - [x] 确保文件编码为 UTF-8
 - [x] 添加了必要的注释

2024-12-28 04:27 UTC, chenranj requested changes

2024-12-28 04:27 UTC, chenranj commented on documentation/tspl/index.md
> +- [阅读中文翻译](https://swiftgg.gitbook.io/swift){:target="_blank"}
这里的中文版我觉得可以改成英文版的，因为中文版本在上面

2024-12-28 04:27 UTC, chenranj commented on documentation/tspl/index.md
> +- [阅读中文翻译](https://swiftgg.gitbook.io/swift){:target="_blank"}
https://docs.swift.org/swift-book/documentation/the-swift-programming-language/

2024-12-28 04:27 UTC, chenranj commented on documentation/tspl/index.md
> +[阅读 The Swift Programming Language](https://docs.swift.org/swift-book/documentation/the-swift-programming-language)
这里换成 SwiftGG 翻译的文档

https://doc.swiftgg.team

2024-12-28 04:27 UTC, chenranj commented on documentation/tspl/index.md
> +欢迎你对书籍的贡献——拉取请求、新问题或对现有主题的评论——请访问 [书籍的 GitHub 仓库](https://github.com/swiftlang/swift-book)。
中文版GitHub repo
https://github.com/SwiftGGTeam/the-swift-programming-language-in-chinese

2024-12-28 04:27 UTC, chenranj commented on documentation/tspl/index.md
> +请通过在 [Swift.org 仓库](https://github.com/swiftlang/swift-org-website) 创建一个问题或提交拉取请求来告知我们。
...来告知 Apple Swift 团队

2024-12-29 10:00 UTC, szupzj18 commented
@chenranj 建议已修改

2024-12-29 17:30 UTC, chenranj approved these changes

2024-12-29 17:30 UTC, merged