docs(translate):  guides
SwiftGGTeam/swift-org-website pull request #74
Opened 2024-12-29 02:38 UTC by king-open

翻译内容

文件路径：/documentation/server/guides
closed [三篇文章](https://github.com/king-open/swift-org-website/commit/deefb45b6ca93075305576afbd2d38ac0d1c563d)

2024-12-29 03:34 UTC, chenranj requested changes

2024-12-29 03:34 UTC, chenranj commented on api/Sources/Run/main.swift
> +
不用修改 swift 文件

2024-12-29 03:34 UTC, chenranj commented on documentation/server/guides/deploying/aws-copilot-fargate-vapor-mongo.md
>  - [AWS Account](https://console.aws.amazon.com/)
AWS 账户？

2024-12-29 03:34 UTC, chenranj commented on documentation/server/guides/deploying/aws-copilot-fargate-vapor-mongo.md
> +## 步骤 7：为数据库凭证创建一个 Copilot 秘密参数
这里的 Secret 应该是和 Copilot 连接在一起的专有名词 Copilot Secret。类似下面一段翻译的 Copilot *secret*。应该保持一致。

2024-12-29 03:34 UTC, chenranj commented on documentation/server/guides/deploying/aws-copilot-fargate-vapor-mongo.md
> +[AWS Copilot](https://aws.github.io/copilot-cli/) Copilot 是一个命令行工具，用于在 AWS 中生成容器化应用程序。您使用 Copilot 来构建和部署您的 Vapor 代码作为 Fargate 中的容器。Copilot 还会为您的 MongoDB 连接字符串的值创建并跟踪一个 AWS Systems Manager 秘密参数。您将此值存储
秘密参数
储存为秘密
加密参数和该值包含数据库的用户名和密码，因此可以加密存储可能更符合逻辑。

2024-12-29 03:34 UTC, chenranj commented on documentation/server/guides/deploying/aws-copilot-fargate-vapor-mongo.md
> +本指南说明了如何在 AWS 上部署 Server-Side Swift 工作负载。该工作负载是一个用于管理待办事项列表的 REST API。它使用 [Vapor](https://vapor.codes/) 框架来编写 API 方法，这些方法将数据存储到 [MongoDB Atlas](https://www.mongodb.com/atlas/database) 云数据库中，并支持数据的检索。
Tacking 翻译成追踪或跟踪更好

2024-12-29 03:34 UTC, chenranj commented on documentation/server/guides/deploying/aws-copilot-fargate-vapor-mongo.md
> +- API Gateway 通过由 AWS Cloud Map 管理的内部 DNS 定位在 AWS Fargate 中的应用容器
这里的从句嵌套翻译可能读的不太通顺？
API Gateway 通过 AWS Cloud Map 内部管理的域名系统（DNS）在 AWS Fargate 中定位您的应用程序容器

2024-12-29 03:34 UTC, chenranj commented on documentation/server/guides/deploying/aws-copilot-fargate-vapor-mongo.md
>  - [MongoDB Atlas Database](https://www.mongodb.com/atlas/database)
MongoDB Atlas 数据库？

这两个虽然是专有名词，但是在其中文官方网站里是“账户”和“数据库”可以考虑修改

2024-12-29 03:34 UTC, chenranj commented on documentation/server/guides/deploying/aws-copilot-fargate-vapor-mongo.md
>  ```swift
上面的“请参阅代码中的注释以理解每个部分的功能。”可以考虑把下面的注释翻译一下

2024-12-29 03:34 UTC, chenranj commented on documentation/server/guides/deploying/aws-copilot-fargate-vapor-mongo.md
> +连接字符串包含您的数据库用户名和密码的占位符。将 *\<password\>**  部分替换为您的数据库密码。然后，创建一个新的 Copilot 秘密参数，命名为 MONGODB_URI，并在提示输入值时保存您的连接字符串。
秘密参数同上。下面类似secret的翻译同上。

2024-12-29 03:34 UTC, chenranj commented on documentation/server/guides/deploying/aws-sam-lambda.md
> +本指南说明了如何使用 Serverless 应用程序模型（SAM） 在 AWS 上部署一个服务器端 Swift 工作负载。 [AWS Serverless Application Model (SAM)](https://aws.amazon.com/serverless/sam/) 工具包。该工作负载是一个用于跟踪待办事项列表的 REST API。它使用 AWS Lambda 部署该 API，
本段使用了Serverless 应用程序模型（SAM）和AWS Serverless Application Model两种翻译。可以考虑保持一致。下同。

2024-12-29 03:34 UTC, chenranj commented on documentation/server/guides/deploying/aws-sam-lambda.md
> +- [AWS Command Line Interface (AWS CLI)](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html) - 安装 CLI 并 [configure](https://docs.aws.amazon.com/cli/latest/userguide/cli-co
多了一个“i”

2024-12-29 03:34 UTC, chenranj commented on documentation/server/guides/deploying/aws-sam-lambda.md
>  AWSTemplateFormatVersion: '2010-09-09'
上文提到了代码的注释，可以考虑翻译一下注释

2025-01-02 09:32 UTC, TsnumiDC commented on documentation/server/guides/testing.md
> +SwiftPM 集成了 [XCTest, Apple’s unit test framework](https://developer.apple.com/documentation/xctest). 在终端运行 `swift test` 或者在 IDE（如 Xcode 或类似工具）中触发测试操作，会运行所有 XCTest 测试用例。测试结果会显示在 IDE 中，或者打印到终端。
Apple’s unit test framework
苹果的单元测试框架

2025-01-02 10:07 UTC, szupzj18 commented on documentation/server/guides/deploying/aws-copilot-fargate-vapor-mongo.md
> +如果您是 MongoDB Atlas 的新用，请按照以下步骤操作 [Getting Started Guide](https://www.mongodb.com/docs/atlas/getting-started/)。您需要创建以下内容：
如果您是 MongoDB Atlas 的**新用户**

2025-01-27 03:50 UTC, merged